package org.hl7.davinci.cdshooks;

import org.hl7.fhir.r4.model.Patient;

import ca.uhn.fhir.rest.api.server.cdshooks.CdsServiceRequestJson;
import ca.uhn.hapi.fhir.cdshooks.api.CdsService;
import ca.uhn.hapi.fhir.cdshooks.api.CdsServicePrefetch;
import ca.uhn.hapi.fhir.cdshooks.api.json.CdsServiceIndicatorEnum;
import ca.uhn.hapi.fhir.cdshooks.api.json.CdsServiceResponseCardJson;
import ca.uhn.hapi.fhir.cdshooks.api.json.CdsServiceResponseJson;

public class OrderSignService {
  
  @CdsService(value = "order-sign-crd",
    hook = "order-sign",
    title = "CRD Order Sign Hook",
    description = "CRD order-sign hook",
    allowAutoFhirClientPrefetch = true,
    prefetch = {
      @CdsServicePrefetch(value = "patient", query = "Patient/{{context.patientId}}")
    }
  )
  public CdsServiceResponseJson handleRequest(CdsServiceRequestJson request) {
    // Implement the logic to handle the order-sign CDS Hook request
    CdsServiceResponseJson response = new CdsServiceResponseJson();
    
    Patient patient = (Patient) request.getPrefetch("patient");

    if (patient == null) {
      throw new IllegalArgumentException("Prefetch patient data is missing");
    }

    String name = patient.getNameFirstRep().getNameAsSingleString();
    if (name == null || name.isEmpty()) {
      name = "unknown";
    }
    response.addCard(new CdsServiceResponseCardJson()
      .setSummary("Example Order Sign Card")
      .setDetail("This is an example card generated by the OrderSignService for patient: " + name)
      .setIndicator(CdsServiceIndicatorEnum.INFO));

    return response;
  }

}
