/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as PasIndexRouteImport } from './routes/pas/index'
import { Route as HooksIndexRouteImport } from './routes/hooks/index'
import { Route as DtrIndexRouteImport } from './routes/dtr/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasIndexRoute = PasIndexRouteImport.update({
  id: '/pas/',
  path: '/pas/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksIndexRoute = HooksIndexRouteImport.update({
  id: '/hooks/',
  path: '/hooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const DtrIndexRoute = DtrIndexRouteImport.update({
  id: '/dtr/',
  path: '/dtr/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dtr/': typeof DtrIndexRoute
  '/hooks/': typeof HooksIndexRoute
  '/pas/': typeof PasIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dtr': typeof DtrIndexRoute
  '/hooks': typeof HooksIndexRoute
  '/pas': typeof PasIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dtr/': typeof DtrIndexRoute
  '/hooks/': typeof HooksIndexRoute
  '/pas/': typeof PasIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dtr/' | '/hooks/' | '/pas/' | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dtr' | '/hooks' | '/pas' | '/resources'
  id: '__root__' | '/' | '/dtr/' | '/hooks/' | '/pas/' | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DtrIndexRoute: typeof DtrIndexRoute
  HooksIndexRoute: typeof HooksIndexRoute
  PasIndexRoute: typeof PasIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pas/': {
      id: '/pas/'
      path: '/pas'
      fullPath: '/pas/'
      preLoaderRoute: typeof PasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/': {
      id: '/hooks/'
      path: '/hooks'
      fullPath: '/hooks/'
      preLoaderRoute: typeof HooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtr/': {
      id: '/dtr/'
      path: '/dtr'
      fullPath: '/dtr/'
      preLoaderRoute: typeof DtrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DtrIndexRoute: DtrIndexRoute,
  HooksIndexRoute: HooksIndexRoute,
  PasIndexRoute: PasIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
